apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: emby
spec:
  selector:
    matchLabels:
      app: emby
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: emby
    spec: 

      containers:
      - name: emby
        image: emby/embyserver
        ports:
        - containerPort: 8096
        volumeMounts: 
        - name: media-movies-35
          mountPath: "/mnt/media-movies"
        - name: media-series-35
          mountPath: "/mnt/media-series"
        - name: audiobooks-35
          mountPath: "/books"
        - name: config-emby-5
          mountPath: "/config"
      volumes: 
      - name: media-movies-35
        persistentVolumeClaim:
         claimName: media-movies-35
      - name: media-series-35
        persistentVolumeClaim:
         claimName: media-series-35
      - name: audiobooks-35
        persistentVolumeClaim:
         claimName: audiobooks-35
      - name: config-emby-5
        persistentVolumeClaim:
         claimName: config-emby-5
