apiVersion: v1 # for versions before 1.9.0 use apps/v1beta2
kind: PersistentVolume
metadata:
  name: pv-nfs-db-bitnami-5
  labels:
   data: db-bitnami-5
spec:
  capacity:
   storage: 1Pi   
  accessModes: 
  - ReadWriteMany
  nfs:
   server: 192.168.0.5
   path: //data/Containers/DB/Bitnami
---
apiVersion: v1 # for versions before 1.9.0 use apps/v1beta2
kind: PersistentVolumeClaim
metadata:
  name: db-bitnami-5
spec:
  accessModes: 
  - ReadWriteMany
  resources:
   requests:
    storage: 1Gi
  selector:
    matchLabels:
     data: db-bitnami-5



---

apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: mariadb
    spec: 

      containers:
      - name: mariadb
        image: bitnami/mariadb:10.3
        ports:
        - containerPort: 3306
        volumeMounts: 
        - name: db-bitnami-5
          mountPath: "/bitnami"
        env: 
        - name: MARIADB_USER
          value: "bn_suitecrm"
        - name: MARIADB_DATABASE
          value: "bitnami_suitecrm"
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
      volumes: 
      - name: db-bitnami-5
        persistentVolumeClaim:
         claimName: db-bitnami-5

---

apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: suitecrm
spec:
  selector:
    matchLabels:
      app: suitecrm
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: suitecrm
    spec: 

      containers:
      - name: suitecrm
        image: bitnami/suitecrm:latest
        ports:
        - containerPort: 80
        volumeMounts: 
        - name: db-bitnami-5
          mountPath: "/bitnami"
        env: 
        - name: MARIADB_HOST
          value: "mariadb"
        - name: MARIADB_PORT_NUMBER
          value: "3306"
        - name: SUITECRM_DATABASE_USER
          value: "bn_suitecrm"
        - name: SUITECRM_DATABASE_NAME
          value: "bitnami_suitecrm"
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
      volumes: 
      - name: db-bitnami-5
        persistentVolumeClaim:
         claimName: db-bitnami-5
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: default
spec:
  ports:
  - nodePort: 3306
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mariadb
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: suitecrm
  namespace: default
spec:
  ports:
  - nodePort: 8095
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: suitecrm
  type: LoadBalancer
status:
  loadBalancer: {}

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: suitecrm-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  tls:
  - hosts:
    - cp.my-net.co.za
    secretName: home-tls
  rules:
  - host: cp.my-net.co.za
    http:
      paths:
      - backend:
          serviceName: suitecrm
          servicePort: 80