apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emby-config-pvc
  labels:
    {{- include "embyserver.labels" . | nindent 4 }}
spec:
  accessModes: 
    - ReadWriteMany
  resources:
   requests:
    storage: 1Pi
  selector:
    matchLabels:
      {{- include "embyserver.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/volume-type: config
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emby-media-pvc
  labels:
    {{- include "embyserver.labels" . | nindent 4 }}
spec:
  accessModes: 
    - ReadWriteMany
  resources:
   requests:
    storage: 1Pi
  selector:
    matchLabels:
      {{- include "embyserver.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/volume-type: media
  storageClassName: ""
