{{- if .Values.rbac.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "embyserver.fullname" . }}
  labels:
    {{- include "embyserver.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: [""]
  verbs: [""]
{{- end }}