{{- if .Values.rbac.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "embyserver.fullname" . }}
  labels:
    {{- include "embyserver.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "embyserver.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "embyserver.serviceAccountName" . }}
{{- end }}